# -*- coding: utf-8 -*-
"""
/***************************************************************************
                        A QGIS Processing plugin provider
                           for GeoProc.com algorithms

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-05-19
        copyright            : (C) 2019-2023 by GeoProc.com
        email                : info@geoproc.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
WARNING: code formatting does not follow pycodestyle recommendations
"""

__author__ = 'GeoProc.com'
__date__ = '20122-04-27'
__copyright__ = '(C) 2019-2023 by GeoProc.com'
__revision__ = '$Format:%H$'

import os
from qgis.PyQt.QtGui import QIcon
from qgis.core import QgsProcessingProvider

from .bcCBar_algorithm             import bcCBarAlgorithm
from .bcclr2tbl_algorithm          import bcclr2tblAlgorithm
from .bcGenRNDSurveyData_algorithm import bcGenRNDSurveyDataAlgorithm
from .bcMultiStyles_algorithm      import bcMultiStylesAlgorithm
from .bcSaveqml_algorithm          import bcSaveqmlAlgorithm
from .bcStackP_algorithm           import bcStackPAlgorithm
from .bcSwapYZ_algorithm           import bcSwapYZAlgorithm
plugin_path = os.path.dirname(__file__)

class thelists(object):
    """ Return some info from current algorithms used to build menu/toolbar. """
    #
    # algorithms to load
    # IMPORTANT: add/remove them from geoprocProvider.loadAlgorithms()
    alglist = [bcCBarAlgorithm(),
               bcclr2tblAlgorithm(),
               bcStackPAlgorithm(),
               bcSwapYZAlgorithm(),
               bcSaveqmlAlgorithm(),
               bcMultiStylesAlgorithm(),
               bcGenRNDSurveyDataAlgorithm(),
              ]

    def get_alglist(self):
        return self.alglist

    def get_icons(self):
        # icons for each of above algorithms
        return [alg._ico for alg in self.alglist]

    def get_tooltips(self):
        # tooltip for each of above algorithms
        return [alg._the_strings["ALGONAME"] for alg in self.alglist]

    def get_algo(self):
        # algorithm name for each of above algorithms
        algname = {}
        for alg in self.alglist:
            algname[alg._the_strings["ALGONAME"]] = alg.name()
        return algname
#=========================================================================================

class geoprocProvider(QgsProcessingProvider):

    def __init__(self):
        """ Initialisation. """
        #
#        super().__init__()
        QgsProcessingProvider.__init__(self)
        self.alglist = thelists.alglist
    #-------------------------------------------------------------------------------------

    def icon(self):
        """ Returns a QIcon for the algorithm. """
        #
        return QIcon(os.path.join(plugin_path, 'res/geoproc.svg'))
    #-------------------------------------------------------------------------------------

    def svgIconPath(self):
        """ Returns a path to an SVG version of the algorithm's icon. """
        #
        return os.path.join(plugin_path, 'res/geoproc.svg')
    #-------------------------------------------------------------------------------------

    def unload(self):
        """ Unloads the provider. Any tear-down steps required by the provider should be
            implemented here.
        """
        #
        pass
    #-------------------------------------------------------------------------------------

    def loadAlgorithms(self):
        """ Loads all algorithms belonging to this provider. """
        #
        # NEVER EVER use a loop to load them:
        # for alg in self.alglist:       NO!
        #     self.addAlgorithm( alg )   NO!
        # If you do that, any call to Settings will generate the following error:
        #  RuntimeError: wrapped C/C++ object of type bcGeoprocAlgos has been deleted
        #
        self.addAlgorithm(bcCBarAlgorithm())
        self.addAlgorithm(bcclr2tblAlgorithm())
        self.addAlgorithm(bcStackPAlgorithm())
        self.addAlgorithm(bcSwapYZAlgorithm())
        self.addAlgorithm(bcSaveqmlAlgorithm())
        self.addAlgorithm(bcMultiStylesAlgorithm())
        self.addAlgorithm(bcGenRNDSurveyDataAlgorithm())
    #-------------------------------------------------------------------------------------

    def id(self):
        """ Returns the unique provider id, used for identifying the provider. """
        #
        return 'GeoProc'
    #-------------------------------------------------------------------------------------

    def name(self):
        """ Returns the provider name, which is used to describe the provider within
            the GUI. """
        #
        return 'GeoProc'
    #-------------------------------------------------------------------------------------

    def longName(self):
        """ Returns a longer version of the provider name. """
        #
        return 'GeoProc provider: collection of QGIS V3.x Processing algorithms.'
#=========================================================================================